export const compensationCopy = {
  hub: {
    title: "Esquemas de compensación",
    description: "Define cómo se paga a cada operador antes de liquidar.",
    settlementsBridge: "Al liquidar se usa el esquema asignado al operador.",
    settlementsLink: "Ir a liquidaciones",
    guideTitle: "Cómo dejar listo el pago a operadores",
    tabs: {
      templates: "Esquemas",
      corridors: "Rutas con tarifa fija",
    },
    steps: [
      "Crea un esquema",
      "Define cómo se paga (reglas o rutas fijas)",
      "Asigna operadores",
    ],
    readiness: {
      ariaLabel: "Estado de configuración del módulo",
      templatesActiveLabel: "esquemas activos",
      templatesIncompleteLabel: "sin pago definido",
      corridorsActiveLabel: "rutas con tarifa fija",
      assignmentsActiveLabel: "operadores con esquema",
    },
    employeeAssignBanner: {
      title: "Este operador aún no tiene esquema de pago",
      description:
        "Llegó desde liquidaciones sin un esquema vigente. Elige abajo uno listo para liquidar y asígnalo, o crea uno nuevo.",
      descriptionNamed:
        "{{name}} no tiene un esquema de pago vigente. Elige abajo uno listo para liquidar y asígnalo, o crea uno nuevo.",
      assignAction: "Asignar a este esquema",
      createAction: "Crear esquema primero",
    },
  },
  templates: {
    title: "Esquemas de compensación",
    description:
      "Esquemas reutilizables que puedes asignar a varios operadores con las mismas reglas.",
    create: "Nuevo esquema",
    emptyTitle: "Aún no hay esquemas de pago",
    emptyDescription:
      "Crea el primero, define cómo se paga y asígnalo a operadores.",
    searchPlaceholder: "Buscar por nombre…",
    filters: {
      statusPlaceholder: "Estado",
      all: "Todos los estados",
      active: "Activos",
      inactive: "Inactivos",
      chipLabel: (value: string) => `Estado: ${value}`,
    },
    columns: {
      name: "Nombre",
      usage: "Uso",
      summary: "Cómo se paga",
      operators: "Operadores",
      actions: "Acciones",
    },
    usage: {
      ready: "Listo para liquidar",
      needsPayment: "Falta definir el pago",
      paused: "Pausado",
    },
    completePayment: "Completar pago",
    edit: "Editar",
    operators: "Operadores",
    operatorsCountLabel: "{{count}} operadores",
    summaryEmpty: "Sin configurar",
    /** Activo/inactivo de asignaciones y corredores (no el listado de esquemas). */
    active: "Activo",
    inactive: "Inactivo",
  },
  compositionCanvas: {
    blocks: {
      rules: "Reglas por ruta",
      allowances: "Prestaciones fijas (opcional)",
      corridors: "Rutas con tarifa fija",
    },
    emptyBlock: "Sin configurar",
    incompleteBadge: "Falta reglas o rutas",
    editingBadge: "Editando",
    incompleteTitle:
      "Para liquidar, agrega reglas por ruta o vincula una ruta con tarifa fija",
    missingSteps: {
      rules: "Agrega al menos una regla por tipo de ruta (opción A)",
      corridors: "Vincula al menos una ruta con tarifa fija (opción B)",
    },
    assignHere: "Asignar operador aquí",
    corridorFallbackTitle: "Ruta vinculada",
    metrics: {
      rules: "reglas",
      allowances: "prestaciones",
      corridors: "rutas",
    },
    expandCard: "Expandir esquema {{name}}",
    collapseCard: "Contraer esquema {{name}}",
    panelRegionLabel: "Composición del esquema {{name}}",
    panel: {
      compositionTitle: "Composición",
      corridorsTitle: "Rutas vinculadas",
    },
    operatorsEditingWarning:
      "Hay cambios sin guardar en la composición. Las prestaciones del esquema pueden no reflejarse en overrides hasta guardar.",
    viewDetail: "Abrir detalle",
    viewDetailSr: "Abrir detalle del esquema {{name}}",
    viewOperators: "Gestionar operadores",
    actions: {
      edit: "Editar esquema",
      duplicate: "Duplicar esquema",
      save: "Guardar",
      savePending: "Guardando…",
      cancelEdit: "Cancelar",
      duplicateSuffix: "(copia)",
    },
  },
  builder: {
    backLabel: "Volver a esquemas",
    sectionsAriaLabel: "Secciones del esquema",
    inspectorTitle: "Resumen",
    canvasAriaLabel: "Área de trabajo del esquema",
    collapseInspectorLabel: "Ocultar resumen",
    pageDescription:
      "Define cuánto se le paga a este operador según el tipo de viaje.",
    statusLabels: {
      complete: "completo",
      partial: "parcial",
      empty: "vacío",
    },
    discard: "Descartar",
    save: "Guardar",
    discardConfirmTitle: "¿Descartar cambios?",
    discardConfirmDescription:
      "Hay cambios sin guardar. Si sales ahora, se perderán.",
    discardConfirmAction: "Descartar cambios",
    discardKeepEditing: "Seguir editando",
    notFoundTitle: "Esquema no encontrado",
    notFoundDescription: "El esquema no existe o no tienes acceso.",
    loadingLabel: "Cargando esquema…",
    noPermissionTitle: "Sin permiso para editar",
    noPermissionDescription: "Necesitas permiso de actualización en liquidaciones.",
    sections: {
      payment: "Pago por tipo de viaje",
      allowances: "Pagos fijos adicionales",
      corridors: "Rutas con precio fijo",
    },
    paymentDescription:
      "Elige un tipo de viaje y cuánto se paga. Ejemplo: foráneo a $3.00 por km.",
    midTripPolicyLabel: "Pago si cambia el operador a mitad del viaje",
    midTripPolicyHint:
      "Por defecto se reparte según km asignados. Si falta km usable, el API usa partes iguales.",
    allowancesDescription:
      "Montos fijos que se suman siempre, sin importar el viaje (comidas, transporte, etc.).",
    corridorsDescription:
      "Si el viaje va por una de estas rutas, se paga el precio fijo en lugar del cálculo por kilómetro.",
    reviewIncomplete:
      "Para poder liquidar con este esquema, agrega al menos un tipo de viaje o vincula una ruta con precio fijo.",
    reviewEmpty: "Sin configuración todavía.",
    inspectorLiveLabel: "Lo que se está armando",
    completenessOk: "Listo para liquidar",
    statusActive: "Activo",
    statusInactive: "Inactivo",
    toggleActiveLabel: "Esquema activo",
    saveErrorTitle: "No se pudo guardar",
    trySchemeTitle: "Vista previa de liquidación",
    trySchemeWithOperator: "Vista previa con {{name}}",
    trySchemeAssignFirst: "Asigna un operador primero para ver la liquidación.",
    trySchemeAssignLink: "Asignar operadores",
    addDescription: "Agregar nota",
    hideDescription: "Ocultar nota",
    identityBlockAriaLabel: "Datos del esquema",
    /** Labels operativos para selects del builder (no tocan enums de settlements). */
    routeTypeLabels: {
      local: "Local",
      long_haul: "Foráneo",
      transfer: "Movimiento local",
    },
    commissionTypeLabels: {
      rate_per_km: "Pago por kilómetro recorrido",
      percentage_of_freight: "Porcentaje de lo que cobra el viaje",
      fixed_per_trip: "Monto fijo por viaje",
      none: "Sin pago extra",
    },
    allowanceTypeLabels: {
      meals: "Comidas",
      transport: "Transporte",
      other: "Otro pago fijo",
    },
    ruleRateLabels: {
      rate_per_km: "Pago por km",
      percentage_of_freight: "Porcentaje",
      fixed_per_trip: "Monto fijo",
      none: "Monto",
    },
    localNoExtraPayNote:
      "Este tipo de viaje no suma un pago extra (el sueldo y los pagos fijos se liquidan aparte).",
    paymentSectionTitle: "Pago por tipo de viaje",
    allowancesSectionTitle: "Pagos fijos adicionales",
    corridorsSectionTitle: "Rutas con precio fijo",
    noPaymentRules: "Sin pagos por tipo de viaje",
    noAllowances: "Sin pagos fijos",
    noCorridors: "Sin rutas con precio fijo",
  },
  operatorsSheet: {
    title: "Operadores — {{name}}",
    description: "Asignaciones vigentes, overrides de prestaciones y asignación masiva.",
  },
  templateDetail: {
    tabs: {
      configuration: "Configuración",
      operators: "Operadores",
    },
    editInHub: "Editar en esquemas",
    editConfiguration: "Editar configuración",
    batchAssign: "Asignar operadores",
    rulesTitle: "Pago por tipo de viaje",
    allowancesTitle: "Pagos fijos adicionales",
    corridorsTitle: "Rutas con precio fijo",
    noRules: "Sin pagos por tipo de viaje",
    noAllowances: "Sin pagos fijos",
    noCorridors: "Sin rutas con precio fijo",
    backLabel: "Esquemas de compensación",
    notFoundTitle: "Esquema no encontrado",
    notFoundDescription: "El esquema solicitado no existe o fue eliminado.",
    configureEmptyTitle: "Configura el esquema de compensación",
    configureEmptyDescription:
      "Agrega un pago por tipo de viaje o vincula rutas con precio fijo; los pagos fijos adicionales son opcionales.",
    configureEmptyCta: "Configurar esquema",
    readOnlyTitle: "Modo solo lectura",
    readOnlyDescription:
      "Puedes consultar la configuración; para editar necesitas permiso de actualización en liquidaciones.",
  },
  corridors: {
    title: "Rutas con tarifa fija",
    description:
      "Catálogo de tarifas por origen y destino. Vincúlalas al editar un esquema.",
    create: "Nueva ruta con tarifa fija",
    emptyTitle: "Sin rutas con tarifa fija",
    emptyDescription:
      "Registra rutas cuando ciertos trayectos no usan comisión por kilómetro.",
    searchPlaceholder: "Buscar ruta…",
    filters: {
      statusPlaceholder: "Estado",
      all: "Todos los estados",
      active: "Activas",
      inactive: "Inactivas",
      chipLabel: (value: string) => `Estado: ${value}`,
    },
    columns: {
      name: "Nombre",
      route: "Origen → destino",
      amount: "Tarifa fija",
      status: "Estado",
      actions: "Acciones",
    },
    duplicateBadge: "Duplicado",
    duplicateBanner:
      "Hay rutas con el mismo origen y destino. Solo una se aplicará en liquidación (la más reciente).",
  },
  corridorActions: {
    openMenuSr: "Abrir menú de acciones de ruta",
    edit: "Editar ruta",
    delete: "Eliminar ruta",
    deleteDialog: {
      title: "¿Eliminar ruta con tarifa fija?",
      description:
        "Solo elimina rutas que no estén vinculadas a esquemas de compensación. Si está en uso, quítala del esquema primero.",
      confirm: "Eliminar",
      pending: "Eliminando…",
      cancel: "Cancelar",
    },
    toasts: {
      deleteSuccess: "Ruta eliminada",
      deleteError: "No se pudo eliminar la ruta",
    },
  },
  templateActions: {
    openMenuSr: "Abrir menú de acciones del esquema",
    delete: "Eliminar esquema",
    deleteDialog: {
      title: "¿Eliminar esquema de compensación?",
      description:
        "Solo elimina esquemas sin operadores asignados ni liquidaciones que lo referencien. Si está en uso, cierra o quita las asignaciones primero.",
      confirm: "Eliminar",
      pending: "Eliminando…",
      cancel: "Cancelar",
    },
    toasts: {
      deleteSuccess: "Esquema eliminado",
      deleteError: "No se pudo eliminar el esquema",
    },
  },
  sheet: {
    templateCreateTitle: "Nuevo esquema",
    templateCreateHelp:
      "Tras guardar defines cómo se paga (reglas, prestaciones y rutas) y luego asignas operadores.",
    templateEditTitle: "Editar configuración",
    templateEditHelp:
      "Define reglas por tipo de ruta, prestaciones fijas y rutas vinculadas. El sueldo se toma de la ficha del operador; crea rutas con tarifa fija en la pestaña Rutas con tarifa fija.",
    schemaDataTitle: "Datos del esquema",
    corridorsSectionHelp:
      "Selecciona rutas del tabulador. Si el viaje coincide, se paga la tarifa fija en lugar de la comisión por km.",
    localNoCommissionNote:
      "Este tipo de viaje no suma comisión adicional al esquema (el sueldo y prestaciones se liquidan aparte).",
    addRule: "Regla",
    addAllowance: "Prestación",
    addFixedPayment: "Pago fijo",
    allowanceType: "Tipo",
    allowanceLabel: "Etiqueta",
    allowanceAmount: "Monto",
    allowancePeriod: "Periodo",
    remove: "Quitar",
    minimumGuaranteed: "Mínimo garantizado",
    corridorCreateTitle: "Nueva ruta con tarifa fija",
    corridorEditTitle: "Editar ruta con tarifa fija",
    corridorHelp:
      "Si el viaje coincide con esta ruta, se paga esta tarifa en lugar de la comisión por kilómetro.",
    batchTitle: "Asignación masiva",
    batchDescription:
      "Selecciona operadores y revisa conflictos de vigencia antes de confirmar.",
    fields: {
      name: "Nombre",
      description: "Descripción",
      templateActive: "Esquema activo",
      corridorActive: "Ruta activa",
      originSection: "Origen",
      destinationSection: "Destino",
      matchType: "Identificar por",
      originRefType: "¿Cómo identificar el origen?",
      originRefValue: "Valor",
      destinationRefType: "¿Cómo identificar el destino?",
      destinationRefValue: "Valor",
      cityPlaceholder: "Ej. Monterrey",
      postalCodePlaceholder: "Ej. 64000",
      branchPlaceholder: "Selecciona sucursal",
      fixedAmount: "Tarifa fija",
      notes: "Notas (opcional)",
      effectiveFrom: "Vigente desde",
      effectiveTo: "Vigente hasta (opcional)",
      closePrevious: "Cerrar asignación anterior al iniciar la nueva",
      reason: "Motivo (opcional)",
      operators: "Operadores",
    },
    ruleRateLabels: {
      rate_per_km: "Tarifa por km",
      percentage_of_freight: "Porcentaje sobre flete",
      fixed_per_trip: "Monto fijo por viaje",
      none: "Monto",
    },
    save: "Guardar",
    savePending: "Guardando…",
    cancel: "Cancelar",
    validationSummary: "Revisa los campos marcados",
    confirmBatch: "Confirmar asignación",
    conflictPreviewTitle: "Conflictos detectados",
    conflictPreviewDescription:
      "Estos operadores tienen otra asignación activa con vigencia traslapada. Se omitirán al confirmar si persiste el conflicto.",
    createCorridorLink: "Crear ruta con tarifa fija",
    manageCorridorsLink: "Gestionar rutas con tarifa fija",
    duplicateConfirmTitle: "¿Guardar ruta duplicada?",
    duplicateConfirmDescription:
      "Ya existe otra ruta con el mismo origen y destino. En liquidación solo se aplicará una (la más reciente).",
    duplicateConfirmAction: "Guardar de todos modos",
    saveForbidden: "No tienes permiso para guardar rutas con tarifa fija.",
  },
  assignments: {
    columns: {
      operator: "Operador",
      effectiveFrom: "Desde",
      effectiveTo: "Hasta",
      status: "Estado",
    },
    active: "Activa",
    inactive: "Inactiva",
    empty:
      "Ningún operador asignado a este esquema. Usa asignación masiva para vincular operadores.",
    emptyTitle: "Sin operadores asignados",
    expandRow: "Expandir fila de prestaciones",
    collapseRow: "Contraer fila de prestaciones",
  },
  assignmentActions: {
    openMenuSr: "Abrir menú de acciones de asignación",
    deactivate: "Desactivar asignación",
    closeValidity: "Cerrar vigencia…",
    delete: "Eliminar asignación",
    deactivateDialog: {
      title: "¿Desactivar asignación?",
      description:
        "La asignación dejará de aplicarse en liquidaciones futuras. No afecta liquidaciones ya creadas.",
      confirm: "Desactivar",
      pending: "Desactivando…",
      cancel: "Cancelar",
    },
    closeValidityDialog: {
      title: "Cerrar vigencia de asignación",
      description: "Indica la última fecha en que este esquema aplica al operador.",
      dateLabel: "Vigente hasta",
      confirm: "Cerrar vigencia",
      pending: "Guardando…",
      cancel: "Cancelar",
    },
    deleteDialog: {
      title: "¿Eliminar asignación?",
      description:
        "Solo elimina asignaciones que no hayan sido usadas en liquidaciones. Si ya se liquidó, cierra la vigencia en su lugar.",
      confirm: "Eliminar",
      pending: "Eliminando…",
      cancel: "Cancelar",
    },
    toasts: {
      deactivateSuccess: "Asignación desactivada",
      deactivateError: "Error al desactivar asignación",
      closeValiditySuccess: "Vigencia cerrada",
      closeValidityError: "Error al cerrar vigencia",
      deleteSuccess: "Asignación eliminada",
      deleteError: "Error al eliminar asignación",
    },
  },
  allowanceOverrides: {
    title: "Suspensión de prestaciones por período",
    description:
      "Suspende una prestación fija para este operador en el rango indicado. La liquidación del período omitirá el monto suspendido.",
    periodStart: "Inicio del período",
    periodEnd: "Fin del período",
    suspendedLabel: "Suspendida",
    activeLabel: "Activa",
    noAllowancesOnTemplate: "Este esquema no define prestaciones fijas.",
    missingAllowanceId: "No se pudo identificar la prestación. Recarga el esquema.",
    toasts: {
      suspended: "Prestación suspendida para el período",
      resumed: "Prestación reactivada para el período",
      error: "Error al actualizar suspensión",
    },
  },
  toasts: {
    templateCreated: "Esquema de compensación creado",
    templateCreateError: "No se pudo crear el esquema de compensación",
    templateUpdated: "Esquema actualizado",
    templateDeleted: "Esquema eliminado",
    corridorCreated: "Ruta creada",
    corridorUpdated: "Ruta actualizada",
    corridorSaveError: "No se pudo guardar la ruta",
    corridorDeleted: "Ruta eliminada",
    batchSuccess: "Asignación completada",
    batchPartial:
      "Asignación parcial: algunos operadores se omitieron por conflicto de vigencia.",
    dataRefreshed: "Datos actualizados",
  },
} as const;
