export const settlementsCopy = {
  title: "Pagos a Operadores",
  description:
    "Calcula y registra los pagos a choferes por sus viajes, descuenta anticipos y lleva el control hasta la transferencia.",
  tabs: {
    settlements: "Liquidaciones",
    advances: "Anticipos pendientes",
    agreements: "Esquemas de compensación",
  },
  workbench: {
    buckets: {
      pending: "Por liquidar",
      draft: "En revisión",
      approval: "En autorización",
      payable: "Listas para pago",
      closed: "Pagadas",
      openAdvances: "Anticipos abiertos",
    },
    bucketDescriptions: {
      pending:
        "Operadores con viajes o sueldo pendiente de liquidar.",
      draft: "Borradores o rechazadas que requieren corrección.",
      approval:
        "Enviadas a la bandeja central de aprobaciones.",
      payable:
        "Autorizadas: falta registrar el pago al operador.",
      closed: "Ya pagadas al operador.",
      openAdvances:
        "Anticipos entregados con saldo pendiente de descontar en liquidaciones.",
    },
    scorecards: {
      settlements: {
        title: "Liquidaciones",
        description:
          "Etapas del pago a operadores: por liquidar, revisión, pago y cerradas.",
        ariaLabel: "Scorecard de liquidaciones",
      },
    },
    openAdvancesBridge: {
      linkLabel: (count: number) =>
        count === 1
          ? "1 anticipo abierto →"
          : `${count} anticipos abiertos →`,
      description:
        "Saldo pendiente de descontar en liquidaciones.",
    },
    bucketDescriptionTooltip: "Qué incluye esta etapa",
    approvalLink: (count: number) =>
      count === 1 ? "1 en autorización →" : `${count} en autorización →`,
    actions: {
      settlePeriod: "Liquidar período",
      reviewInApprovals: "Revisar en aprobaciones",
      viewFullHistory: "Historial",
      backToWorkbench: "Volver a pagos pendientes",
      includeContractors: "Incluir contratistas",
    },
    backlog: {
      tableAriaLabel: "Operadores pendientes de liquidar",
      periodTooltips: {
        trips_pending:
          "Período sugerido según la frecuencia de sueldo del esquema del operador y la salida del viaje más antiguo pendiente (semana, quincena o mes calendario, según corresponda).",
        salary_close:
          "Período del último corte de sueldo vencido, según la frecuencia configurada en el esquema del operador.",
        mixed:
          "Período sugerido por los viajes pendientes. El registro puede incluir además el cierre de sueldo del corte anterior.",
      },
      periodTooltipFallback: "Período sugerido para esta liquidación.",
      rowTypes: {
        trips_pending: (count: number) =>
          count === 1 ? "1 viaje pendiente" : `${count} viajes pendientes`,
        salary_close: "Cierre de sueldo",
        mixed: "Viajes + sueldo",
      },
      ageDays: (days: number) =>
        days === 1 ? "1 día" : `${days} días`,
      estimatedAmountMissing: "—",
      correctBadge: "Corregir",
    },
    warnings: {
      no_client_invoice: "Sin factura de cliente",
      period_overlap: "Solapamiento de períodos",
      open_advance: "Anticipo por descontar",
    },
    empty: {
      backlogTitle: "Sin operadores pendientes de liquidar",
      backlogDescription:
        "Todos los operadores están al corriente para este filtro. Revisa anticipos pendientes o consulta el historial.",
      backlogApiPendingTitle: "Lista en preparación",
      backlogApiPendingDescription:
        "La lista de operadores por liquidar se está preparando. Mientras tanto, revisa las liquidaciones ya registradas o el historial.",
      pipelineTitle: "Sin liquidaciones en esta etapa",
      pipelineDescription:
        "No hay liquidaciones en esta etapa. Prueba otra o consulta el historial.",
      approvalCtaTitle: "Autorizaciones centralizadas",
      approvalCtaDescription:
        "Las liquidaciones por autorizar se gestionan en la bandeja de aprobaciones de Finanzas.",
      goToApprovals: "Ir a aprobaciones",
      schemesBridgeTitle: "¿Listo para liquidar?",
      schemesBridgeDescription:
        "Si aún no hay operadores por liquidar, revisa que tengan esquema de compensación asignado y sueldo base en la ficha del empleado.",
      schemesBridgeAction: "Ir a esquemas de compensación",
    },
    readiness: {
      title: "Antes de liquidar, verifica que la configuración esté completa.",
      ariaLabel: "Prerrequisitos para liquidar operadores",
      chipsAriaLabel: "Estado de configuración de liquidaciones",
      operatorsSalaryLabel: "operadores activos (sueldo en ficha)",
      templatesActiveLabel: "esquemas de compensación activos",
      assignmentsActiveLabel: "operadores asignados a un esquema",
      tripsCompletedLabel: "viajes completados",
      relatedConfigDescription:
        "Esquemas y asignación de operadores",
      cta: {
        operatorsSalary: "Ir a Empleados",
        templatesActive: "Ir a Esquemas",
        assignmentsActive: "Ir a Esquemas → Operadores",
        tripsCompleted: "Ir a Viajes",
        generic: "Revisar",
      },
    },
  },
  actions: {
    createSettlement: "Nueva liquidación",
    createAdvance: "Registrar anticipo",
    createAgreement: "Nuevo esquema",
    manageAgreements: "Esquemas de compensación",
    calculatePreview: "Calcular vista previa del pago",
    approve: "Autorizar",
    reject: "Rechazar",
    disburse: "Registrar pago al operador",
    saveDraft: "Guardar como borrador",
    submitApproval: "Enviar para autorización",
    cancelSettlement: "Cancelar liquidación",
    cancel: "Cancelar",
    confirm: "Confirmar",
    backToList: "Volver a liquidaciones",
    viewDetail: "Ver detalle",
    viewDetails: "Ver detalles",
    exportCsv: "Exportar CSV",
    sendToApproval: "Enviar a autorización",
    authorizeAdvance: "Autorizar anticipo",
    rejectAdvance: "Rechazar anticipo",
    recordAdvanceDisbursement: "Registrar entrega / pago",
    viewDriverFile: "Ver expediente chofer",
    viewTripPrefix: "Ver viaje",
    openActionsMenuSr: "Abrir menú de acciones",
  },
  status: {
    draft: "Borrador",
    pending_approval: "Por autorizar",
    approved: "Autorizada",
    disbursed: "Pagada",
    rejected: "Rechazada",
    cancelled: "Cancelada",
  },
  advanceStatus: {
    pending_disbursement: "Pendiente",
    disbursed: "Entregado (por descontar)",
    partially_applied: "Parcialmente descontado",
    fully_applied: "Descontado al 100%",
    cancelled: "Cancelado",
  },
  fields: {
    employee: "Operador",
    period: "Período de liquidación",
    periodStart: "Fecha inicio",
    periodEnd: "Fecha fin",
    settlementNumber: "Folio de liquidación",
    folio: "Folio de anticipo",
    amount: "Monto entregado",
    netAmount: "A pagar",
    grossAmount: "Lo ganado",
    totalDeductions: "Deducciones totales",
    totalCommissions: "Pago por viajes realizados",
    totalReimbursements: "Gastos y casetas por reembolsar",
    totalAdvances: "Anticipos descontados",
    totalBonuses: "Bonos e incentivos",
    tripsCount: "Viajes realizados",
    calculationType: "Regla de pago",
    baseRate: "Tarifa fija por viaje",
    ratePerKm: "Tarifa por km recorrido",
    percentageRate: "% sobre flete facturado",
    helperDailyRate: "Tarifa diaria ayudante",
    paymentMethod: "Método de entrega",
    bankReference: "Referencia de pago (transferencia o folio)",
    notes: "Observaciones / Notas",
    category: "Categoría de anticipo",
    balanceRemaining: "Saldo por descontar",
    tripCode: "Viaje",
    route: "Ruta del viaje",
    distance: "Distancia (km)",
    freightRevenue: "Flete facturado",
    status: "Estado",
    action: "Acción",
    deliveryDate: "Fecha de entrega",
    validity: "Vigencia",
    rateFormula: "Tarifa / Fórmula",
    schemeSalary: "Esquema / Sueldo",
    commissionRules: "Reglas de comisión",
    noFixedSalary: "Sin sueldo base",
    compositeScheme: "Sueldo + pago por viajes",
    noCommission: "Sin comisión",
    minGuaranteedPrefix: "mín.",
    salaryOnly: "Solo sueldo base",
    fromPrefix: "Desde",
    toPrefix: "hasta",
    allStatuses: "Todos los estados",
    activeStatus: "Activo",
    inactiveStatus: "Inactivo",
    overlapConflictStatus: "Conflicto de vigencia",
    searchPlaceholder: "Buscar por operador, folio o viaje...",
    pendingConcept: "Concepto pendiente",
    estimatedAmount: "A pagar (est.)",
  },
  toasts: {
    dataRefreshed: "Datos actualizados",
    exportSettlementsSuccess: "Archivo CSV de liquidaciones generado",
    exportAdvancesSuccess: "Archivo CSV de anticipos generado",
    noSettlementsToExport: "No hay liquidaciones para exportar",
    noAdvancesToExport: "No hay anticipos para exportar",
    approveSettlementSuccess: "Liquidación autorizada correctamente",
    approveSettlementError: "Error al autorizar liquidación",
    rejectSettlementSuccess: "Liquidación rechazada",
    rejectSettlementError: "Error al rechazar liquidación",
    rejectSettlementReasonRequired: "Especifica el motivo del rechazo",
    submitSettlementSuccess: "Liquidación enviada a autorización",
    submitSettlementError: "Error al enviar liquidación a autorización",
    cancelSettlementSuccess: "Liquidación cancelada",
    cancelSettlementError: "Error al cancelar liquidación",
    submitAdvanceSuccess: "Anticipo enviado a autorización",
    submitAdvanceError: "Error al enviar anticipo",
    approveAdvanceSuccess: "Anticipo autorizado correctamente",
    approveAdvanceError: "Error al autorizar anticipo",
    rejectAdvanceSuccess: "Anticipo rechazado",
    rejectAdvanceError: "Error al rechazar anticipo",
    rejectAdvanceReasonRequired: "Especifica el motivo del rechazo",
    disburseAdvanceSuccess: "Anticipo entregado correctamente",
    disburseAdvanceError: "Error al registrar entrega de anticipo",
    selfApprovalNotAllowedAuthorize: "No puedes autorizar un anticipo que tú mismo enviaste",
    selfApprovalNotAllowedReject: "No puedes rechazar un anticipo que tú mismo enviaste",
    selfApprovalBadge: "Auto-aprobación no permitida",
    selfApprovalSettlementAuthorize:
      "No puedes autorizar una liquidación que tú mismo enviaste",
    selfApprovalSettlementReject:
      "No puedes rechazar una liquidación que tú mismo enviaste",
  },
  actionDialogs: {
    approveSettlement: {
      title: "¿Autorizar liquidación?",
      descriptionPart1: "Estás por autorizar el folio",
      descriptionPart2: "del operador",
      descriptionPart3: "por un monto neto de",
      descriptionPart4:
        ". Una vez autorizada, quedará lista para que tesorería registre el pago al operador.",
      confirm: "Sí, autorizar liquidación",
      pending: "Autorizando...",
      cancel: "Cancelar",
    },
    cancelSettlement: {
      title: "¿Cancelar liquidación?",
      descriptionPart1: "Se cancelará el folio",
      descriptionPart2:
        "en borrador. Los anticipos deducidos (si los hay) se restaurarán. Esta acción no se puede deshacer.",
      confirm: "Sí, cancelar liquidación",
      pending: "Cancelando...",
      cancel: "Volver",
    },
    rejectSettlement: {
      title: "Rechazar liquidación",
      descriptionPrefix: "Especifica el motivo por el cual no se autoriza el folio",
      reasonLabel: "Motivo de rechazo *",
      reasonPlaceholder: "Ej. Falta comprobante de casetas o ajuste en km...",
      confirm: "Confirmar rechazo",
      pending: "Rechazando...",
      cancel: "Cancelar",
    },
    rejectAdvance: {
      title: "Rechazar anticipo",
      descriptionPrefix: "Especifica el motivo por el cual no se autoriza el anticipo",
      reasonLabel: "Motivo de rechazo *",
      reasonPlaceholder: "Ej. Excede el tope semanal de viáticos o viaje cancelado...",
      confirm: "Confirmar rechazo",
      pending: "Rechazando...",
      cancel: "Cancelar",
    },
    disburseAdvance: {
      title: "Registrar entrega de anticipo",
      descriptionPart1: "Confirma la entrega o transferencia de",
      descriptionPart2: "al operador",
      bankRefLabel: "Referencia / Folio SPEI",
      bankRefPlaceholder: "Ej. SPEI-992811",
      confirm: "Confirmar entrega",
      pending: "Registrando...",
      cancel: "Cancelar",
    },
    deactivateAgreement: {
      title: "¿Desactivar tarifa?",
      description:
        "La tarifa dejará de aplicarse en liquidaciones futuras. El pago ya registrado no cambia.",
      confirm: "Desactivar tarifa",
      pending: "Desactivando...",
      cancel: "Cancelar",
    },
    closeAgreementValidity: {
      title: "Cerrar vigencia de tarifa",
      description:
        "Define la fecha fin de vigencia. A partir del día siguiente dejará de ser elegible para liquidaciones nuevas.",
      dateLabel: "Fin de vigencia *",
      confirm: "Cerrar vigencia",
      pending: "Guardando...",
      cancel: "Cancelar",
    },
    deleteAgreement: {
      title: "¿Eliminar tarifa?",
      description:
        "Esta acción es permanente. Solo elimina tarifas que no hayan sido usadas en liquidaciones. Si ya se liquidó con esta tarifa, desactívala o cierra su vigencia.",
      confirm: "Eliminar tarifa",
      pending: "Eliminando...",
      cancel: "Cancelar",
    },
  },
  agreementGovernance: {
    overlapCreateTitle: "Hay otra tarifa activa con vigencia traslapada",
    overlapCreateDescription:
      "Este operador ya tiene tarifa(s) activa(s) que cubren parte del rango que estás creando. Para evitar ambigüedad en liquidación, cierra la anterior o desactívala después de guardar.",
    overlapCreateClosePreviousLabel:
      "Cerrar la(s) tarifa(s) anterior(es) al día previo del inicio de esta",
    settlementAmbiguityTitle: "Varias asignaciones vigentes en la fecha fin del período",
    settlementAmbiguityDescriptionPrefix:
      "El cálculo del pago aplica la asignación más reciente por vigencia (desde",
    settlementAmbiguityDescriptionSuffix:
      "). Revisa las asignaciones del operador en Esquemas de compensación.",
    reviewAgreementsAction: "Revisar esquemas de compensación",
    actions: {
      deactivate: "Desactivar tarifa",
      closeValidity: "Cerrar vigencia…",
      delete: "Eliminar tarifa",
    },
    toasts: {
      deactivateSuccess: "Tarifa desactivada",
      deactivateError: "Error al desactivar tarifa",
      closeValiditySuccess: "Vigencia cerrada",
      closeValidityError: "Error al cerrar vigencia",
      deleteSuccess: "Tarifa eliminada",
      deleteError: "Error al eliminar tarifa",
      closePreviousOnCreateError: "No se pudo cerrar la tarifa anterior",
    },
  },
  confirmSubmitDialog: {
    title: "¿Enviar liquidación para autorización?",
    description: "Revisa el monto a pagar antes de enviar a la bandeja de autorizaciones.",
    confirmAction: "Confirmar y enviar",
  },
  empty: {
    settlements: "No hay liquidaciones registradas en este período.",
    advances: "No hay anticipos pendientes para este operador.",
    agreements:
      "Ningún operador tiene un esquema de compensación asignado. Usa asignación masiva para vincular operadores.",
    trips: "No se encontraron viajes completados pendientes de liquidar para este operador en las fechas seleccionadas.",
    selectOperatorPrompt: "Selecciona un operador y un rango de fechas para calcular el pago automáticamente.",
    settlementsTitle: "No hay liquidaciones registradas",
    advancesTitle: "No hay anticipos pendientes",
    agreementsTitle: "Sin asignaciones de esquema",
  },
  agreementsPage: {
    title: "Tarifas de operadores",
    description:
      "Configura sueldos base y comisiones por tipo de viaje para cada operador.",
  },
  detailPage: {
    balanceStrip: {
      grossEarnings: "Lo ganado",
      grossEarningsSubtext: "Sueldo, viajes y reembolsos del período",
      advancesDeducted: "Anticipos",
      advancesSubtext: "Descontados en este pago",
      netToPay: "A pagar",
      netSubtext: "Lo que recibe el operador",
    },
    workflow: {
      title: "Progreso del pago",
      step1: "Elaboró",
      step2: "Autorizó",
      step3: "Pagó",
      pendingManagement: "Pendiente de gerencia",
      pendingDisbursement: "Pendiente de pago",
      notDisbursed: "Sin pago",
      notApproved: "Sin autorizar",
    },
    paymentInfo: {
      title: "Pago registrado",
      method: "Método",
      reference: "Referencia",
      disbursedAt: "Fecha",
    },
    tariff: {
      title: "Cómo se calculó este pago",
      subtitle: "Acuerdo aplicado al momento del cálculo.",
      expandLabel: "Ver acuerdo aplicado",
      collapseLabel: "Ocultar acuerdo",
      disclaimer: "Registrado al calcular este pago; no cambia si editas tarifas después.",
      scheme: "Acuerdo:",
      fixedSalary: "Sueldo base:",
      routesTitle: "Pago por tipo de ruta:",
      ratePerKm: "Tarifa por kilómetro:",
      percentageRate: "% sobre flete:",
      fixedPerTrip: "Tarifa fija por viaje:",
      helperDailyRate: "Tarifa diaria ayudante:",
      compositeLabel: "Sueldo + pago por viajes",
    },
    items: {
      title: "Desglose",
      subtitle: "Conceptos de lo ganado y anticipos descontados.",
      expandLabel: "Ver desglose",
      collapseLabel: "Ocultar desglose",
      earningsTitle: "1. Ingresos del período (+)",
      earningsSubtitle: "Sueldo base, viajes y gastos reembolsables.",
      deductionsTitle: "2. Anticipos descontados (−)",
      deductionsSubtitle: "Anticipos y viáticos de este corte.",
      subtotalEarnings: "Subtotal ingresos:",
      subtotalDeductions: "Subtotal descuentos:",
      emptyEarnings: "No hay ingresos desglosados en esta liquidación.",
      emptyDeductions: "No se descontaron anticipos en esta liquidación.",
      earningsTableAriaLabel: "Desglose de ingresos",
      deductionsTableAriaLabel: "Desglose de anticipos descontados",
      headerConcept: "Concepto",
      headerCategory: "Categoría",
      headerTripReference: "Viaje / Referencia",
      headerAdvanceReference: "Referencia / Anticipo",
      headerQuantity: "Cantidad",
      headerUnitRate: "Tarifa unit.",
      headerAmount: "Importe",
      headerDeductedAmount: "Monto descontado",
      countConceptSingular: "concepto",
      countConceptPlural: "conceptos",
      countDeductionSingular: "descuento",
      countDeductionPlural: "descuentos",
      viewTripFallback: "Ver viaje",
      linkedAdvanceFallback: "Anticipo vinculado",
      guaranteedBaseSalary: "Sueldo base garantizado",
      tripCommissionTitle: "Pago por viaje",
      reimbursementPrefix: "Reembolso",
      advanceDeductionTitle: "Descuento de anticipo",
      receiptPrefix: "Comprobante",
    },
    rejection: {
      title: "Liquidación rechazada por gerencia",
      reasonLabel: "Motivo:",
      reopenDraftBtn: "Reabrir como borrador y corregir",
    },
    notes: {
      title: "Observaciones y notas de patio",
      noNotes: "Sin observaciones registradas.",
    },
    receipt: {
      documentTitle: "Liquidación de Viajes y Pago a Operador",
      documentSubtitle: "Comprobante operativo de liquidación de viajes y finiquito del período",
      folioLabel: "FOLIO:",
      statusLabel: "Estado:",
      issueDateLabel: "Emisión:",
      driverLabel: "Operador / Conductor:",
      settledPeriodLabel: "Período Liquidado:",
      paymentMethodLabel: "Método de pago:",
      bankRefLabel: "Ref. de pago:",
      earningsTitle: "1. Ingresos del Período (Sueldo, Viajes y Reembolsos) (+)",
      earningsTable: {
        concept: "Concepto / Detalle",
        type: "Tipo",
        trip: "Viaje",
        quantity: "Cant.",
        rate: "Tarifa",
        amount: "Importe",
        empty: "Sin ingresos ni viajes registrados en este período",
        subtotal: "Subtotal Ingresos (+):",
      },
      deductionsTitle: "2. Descuentos y Anticipos de Viaje (−)",
      deductionsTable: {
        concept: "Concepto",
        type: "Tipo",
        reference: "Folio / Referencia",
        amount: "Monto Descontado",
        empty: "Sin deducciones ni anticipos aplicados",
        subtotal: "Total Descuentos (−):",
      },
      balance: {
        totalEarningsLabel: "(+) Total Ingresos",
        totalDeductionsLabel: "(−) Total Descuentos",
        netToPayLabel: "(=) NETO A PAGAR AL OPERADOR",
      },
      notesTitle: "Observaciones / Acuerdos de liquidación:",
      signatures: {
        driverTitle: "Firma de Conformidad del Operador",
        driverDisclaimer:
          "Recibí a mi entera satisfacción la cantidad neta indicada por concepto de mis servicios y viajes del período.",
        approverTitle: "Revisado y Autorizado / Empresa",
        approverDefaultName: "Tesorería / Operaciones",
        approverDisclaimerDisbursed: "Liquidación revisada y pagada por administración.",
        approverDisclaimerPending: "Liquidación autorizada, pendiente de pago.",
        disbursedOnPrefix: "Pagado el",
      },
    },
  },
  createPage: {
    header: {
      title: "Nueva liquidación a operador",
      subtitle: "Calcula lo ganado por viajes y descuenta anticipos entregados.",
    },
    sections: {
      filtersTitle: "1. Operador y período",
      filtersDescription: "Selecciona el operador y el rango de fechas para consultar viajes y anticipos abiertos.",
      agreementActiveLabel: "Acuerdo de pago activo",
      templateActivePrefix: "Esquema",
      agreementProfileSalaryHint:
        "El sueldo base se toma de la ficha del empleado al liquidar; asigna un esquema de compensación si aún no tiene uno.",
      agreementProfileSalaryHintLink: "Abrir ficha del empleado para configurar sueldo base",
      tripsTitle: "2. Viajes del período",
      tripsDescription:
        "Viajes finalizados con pago calculado según el acuerdo del operador.",
      tripsShowCalcDetail: "Ver detalle de cálculo",
      tripsHideCalcDetail: "Ocultar detalle de cálculo",
      advancesTitle: "3. Anticipos por descontar",
      advancesDescription: "Elige qué anticipos descontar de este pago y ajusta montos si hace falta.",
      notesTitle: "4. Observaciones",
      notesPlaceholder: "Instrucciones para tesorería, cuentas o acuerdos especiales...",
    },
    summary: {
      cardTitle: "Resumen a pagar",
      cardSubtitle: "Cálculo en vivo",
      earnedLabel: "Lo ganado",
      advancesLabel: "Anticipos",
      netTotalLabel: "A pagar",
      netTotalSubtext: "Lo que recibirá el operador",
      earnedBreakdownTitle: "Detalle de lo ganado",
      fixedSalaryLabel: "Sueldo base",
      fixedAllowancesLabel: "Prestaciones fijas",
      commissionsLabel: "Pago por viajes",
      reimbursementsLabel: "Reembolsos",
      submitApprovalBtn: "Enviar para autorización",
      submitApprovalSegregationHint:
        "Otro usuario con permiso de autorizar en Finanzas debe revisar esta liquidación.",
      saveDraftBtn: "Guardar borrador",
      cancelBtn: "Cancelar",
      noItemsToSettle: "No hay viajes ni sueldo base para liquidar en este período.",
      actionsBlockedUntilReady:
        "Configura un esquema de compensación válido para guardar o enviar, o confirma el registro solo de reembolsos.",
      reimbursementsOnlyLabel:
        "Registrar solo reembolsos y anticipos (pago de sueldo pendiente de esquema)",
      reimbursementsOnlyHint:
        "La liquidación no incluirá sueldo base ni pago por viajes hasta que exista un esquema completo.",
    },
    advances: {
      selectAll: "Descontar todo",
      clearAll: "Quitar descuentos",
      remainingNote: "Quedará saldo pendiente:",
      emptyAdvances: "El operador no tiene anticipos pendientes de descontar.",
    },
    trips: {
      coveredBySalary: "Cubierto por sueldo base",
      emptyTrips: "No hay viajes completados pendientes de liquidar para este operador en las fechas seleccionadas.",
      supportParticipationBadge: "Apoyo",
      corridorBadgePrefix: "Corredor",
      tripCol: "Viaje",
      routeCol: "Ruta / Tipo",
      payCol: "A pagar",
      reimbursementsCol: "Reembolsos",
      ruleCol: "Regla de pago",
      opsDetailCol: "Detalle",
    },
    dialog: {
      title: "¿Confirmar y enviar?",
      description: "Revisa el monto a pagar antes de enviar a autorización.",
      driverLabel: "Operador",
      periodLabel: "Período",
      netLabel: "A pagar",
      confirmAction: "Confirmar y enviar",
      cancelAction: "Regresar a editar",
    },
    empty: {
      selectOperatorTitle: "Selecciona un operador",
      selectOperatorDescription: "Elige operador y fechas para calcular el pago automáticamente.",
      calculatingTitle: "Calculando el pago…",
      calculatingDescription: "Consultando viajes concluidos y anticipos abiertos.",
      previewErrorTitle: "No se pudo calcular el pago",
      noAgreementTitle: "Sin esquema de compensación",
      noAgreementDescription:
        "No hay un esquema asignado para este operador en el período seleccionado. Asigna un esquema de compensación antes de liquidar.",
      missingSchemeTitle: "Sin esquema de compensación",
      missingSchemeDescription:
        "El operador no tiene un esquema asignado vigente para este período. Crea o asigna un esquema en Finanzas antes de liquidar sueldo, comisiones o prestaciones.",
      incompleteAgreementTitle: "Esquema de compensación incompleto",
      incompleteAgreementDescription:
        "Hay un esquema asignado, pero no define montos liquidables en el período. Completa reglas, prestaciones o sueldo en empleados antes de autorizar.",
      configureAgreementAction: "Ir a esquemas de compensación",
      configureCompensationAction: "Ir a esquemas de compensación",
      configureEmployeeSalaryAction: "Configurar sueldo en empleado",
    },
    toasts: {
      missingRequiredParams: "Completa los datos del operador y rango de fechas",
      submitSuccess: "Liquidación enviada para autorización",
      draftSuccess: "Liquidación guardada como borrador",
      createError: "Error al generar liquidación",
      agreementRequired: "Asigna un esquema de compensación o confirma el registro solo de reembolsos",
    },
  },
  agreementsDialog: {
    title: "Configurar tarifa de operador",
    description: "Define el sueldo base recurrente y las comisiones por tipo de viaje para este operador.",
    employeeLabel: "Operador / Conductor *",
    employeePlaceholder: "Seleccionar operador",
    fixedSalarySectionTitle: "Sueldo base recurrente",
    fixedSalarySectionDescription: "Ingreso fijo periódico garantizado al chofer independientemente de los viajes.",
    fixedSalarySuggestedNotice: "Monto y frecuencia sugeridos según la ficha laboral del operador.",
    fixedSalaryAmountLabel: "Monto de sueldo base ($)",
    fixedSalaryPeriodLabel: "Frecuencia de pago",
    fixedSalaryGuaranteedLabel: "Sueldo 100% garantizado (se paga íntegro aunque no haya viajes en el período)",
    routesSectionTitle: "Comisiones por tipo de viaje",
    routesSectionDescription: "Reglas aplicadas automáticamente según la clasificación del viaje (Foráneo, Local o Transfer).",
    addRuleButton: "Agregar condición de ruta",
    routeTypeLabel: "Tipo de viaje",
    calculationTypeLabel: "Tipo de comisión",
    calculationTypePlaceholder: "Seleccionar tipo de comisión",
    ratePerKmLabel: "Tarifa por kilómetro ($/km)",
    percentageRateLabel: "% de comisión sobre flete",
    baseRateLabel: "Tarifa fija por viaje ($)",
    helperDailyRateLabel: "Tarifa diaria / ayudante ($/día)",
    minimumGuaranteedLabel: "Garantía mínima por viaje ($)",
    localCoveredNote: "Este tipo de viaje queda cubierto íntegramente por el sueldo base recurrente (sin comisión adicional).",
    effectiveFromLabel: "Inicio de vigencia *",
    effectiveToLabel: "Fin de vigencia (opcional)",
    notesLabel: "Observaciones / Acuerdos adicionales",
    notesPlaceholder: "Detalles sobre acuerdos de viáticos, bono de rendimiento o condiciones especiales...",
    saving: "Guardando tarifa...",
    save: "Guardar tarifa de operador",
    toastSuccess: "Tarifa de operador guardada exitosamente",
    toastErrorTitle: "Error al registrar tarifa",
  },
  advancesDialog: {
    title: "Registrar anticipo a operador",
    description: "Captura los datos del anticipo de viaje o viáticos entregados al operador.",
    employeeLabel: "Operador / Empleado *",
    employeePlaceholder: "Seleccionar operador",
    amountLabel: "Monto ($) *",
    categoryLabel: "Categoría *",
    categoryPlaceholder: "Categoría",
    paymentMethodLabel: "Método de entrega *",
    paymentMethodPlaceholder: "Método",
    bankReferenceLabel: "Referencia bancaria / Folio",
    bankReferencePlaceholder: "Ej. SPEI 889922",
    notesLabel: "Notas / Justificación",
    notesPlaceholder: "Detalles del viaje o motivo de la entrega...",
    saving: "Guardando...",
    save: "Registrar anticipo",
    toastSuccess: "Anticipo registrado exitosamente",
    toastErrorTitle: "Error al registrar anticipo",
  },
} as const;
