export {
  VehicleStatus,
  VehicleType,
  type Vehicle,
  type VehicleListItem,
  type VehicleStatusType,
  type VehicleTypeValue,
  type CreateVehiclePayload,
  type UpdateVehiclePayload,
  type VehicleFilters,
  type VehicleQueryParams,
  type AssignableVehicleItem,
  vehicleQueryKeys,
  VEHICLE_STATUS_LABELS,
  VEHICLE_TYPE_LABELS,
  VEHICLE_STATUS_COLORS,
  VALID_STATUS_TRANSITIONS,
} from "./entities";
