/**
 * Application Layer - Public API
 * Clean Architecture
 *
 * Exporta todos los casos de uso
 */

// React Query hooks
export {
  CargoError,
  ExpenseError,
  TripActionError,
  TripCreationError,
  useAddCargo,
  useAddCargoMovement,
  useAddExpense,
  useAddMultipleCargos,
  useAddMultipleExpenses,
  useApproveExpense,
  useCancelTrip,
  useCompleteCargoMovement,
  useCreateTrip,
  useDeleteCargo,
  useDeleteExpense,
  useDeleteTrip,
  useFinishTrip,
  useRegisterTrackingEvent,
  useRejectExpense,
  useScheduleTrip,
  useStartTrip,
  useTrip,
  useTripCargos,
  useTripExpenses,
  useTripExpensesSummary,
  useTripTimeline,
  useTrips,
  useUpdateCargo,
  useUpdateExpense,
  useUpdateTrip,
  useUpdateTripStatus,
} from "./hooks";

// Use Cases
export {
  AddCargoMovementUseCase,
  AddCargoUseCase,
  AddExpenseUseCase,
  AddStopUseCase,
  ApproveExpenseUseCase,
  CancelTripUseCase,
  CompleteCargoMovementUseCase,
  //   CreateCargoInput,
  //   CreateCargoMovementInput,
  //   CreateExpenseInput,
  //   CreateStopInput,
  //   CreateTripInput,
  CreateTripUseCase,
  DeleteCargoUseCase,
  DeleteExpenseUseCase,
  DeleteStopUseCase,
  DeleteTripUseCase,
  //   FinishTripInput,
  FinishTripUseCase,
  GetCargosUseCase,
  GetExpensesSummaryUseCase,
  GetExpensesUseCase,
  GetStopsUseCase,
  GetTripByIdUseCase,
  GetTripsUseCase,
  //   IAddCargoMovementUseCase,
  //   IAddCargoUseCase,
  //   IAddExpenseUseCase,
  //   IAddStopUseCase,
  //   IApproveExpenseUseCase,
  //   ICancelTripUseCase,
  //   ICompleteCargoMovementUseCase,
  //   ICreateTripUseCase,
  //   IDeleteCargoUseCase,
  //   IDeleteExpenseUseCase,
  //   IDeleteStopUseCase,
  //   IDeleteTripUseCase,
  //   IFinishTripUseCase,
  //   IGetCargosUseCase,
  //   IGetExpensesSummaryUseCase,
  //   IGetExpensesUseCase,
  //   IGetStopsUseCase,
  //   IGetTripByIdUseCase,
  //   IGetTripsUseCase,
  //   IMarkStopVisitedUseCase,
  //   IRejectExpenseUseCase,
  //   IReorderStopsUseCase,
  //   IScheduleTripUseCase,
  //   IStartTripUseCase,
  //   IUpdateCargoUseCase,
  //   IUpdateExpenseUseCase,
  //   IUpdateStopUseCase,
  //   IUpdateTripStatusUseCase,
  //   IUpdateTripUseCase,
  MarkStopVisitedUseCase,
  RejectExpenseUseCase,
  ReorderStopsUseCase,
  ScheduleTripUseCase,
  StartTripUseCase,
  //   UpdateCargoInput,
  UpdateCargoUseCase,
  //   UpdateExpenseInput,
  UpdateExpenseUseCase,
  UpdateStopUseCase,
  //   UpdateTripInput,
  //   UpdateTripStatusInput,
  UpdateTripStatusUseCase,
  UpdateTripUseCase,
  createAddCargoMovementUseCase,
  createAddCargoUseCase,
  createAddExpenseUseCase,
  createAddStopUseCase,
  createApproveExpenseUseCase,
  createCancelTripUseCase,
  createCompleteCargoMovementUseCase,
  createCreateTripUseCase,
  createDeleteCargoUseCase,
  createDeleteExpenseUseCase,
  createDeleteStopUseCase,
  createDeleteTripUseCase,
  createFinishTripUseCase,
  createGetCargosUseCase,
  createGetExpensesSummaryUseCase,
  createGetExpensesUseCase,
  createGetStopsUseCase,
  createGetTripByIdUseCase,
  createGetTripsUseCase,
  createMarkStopVisitedUseCase,
  createRejectExpenseUseCase,
  createReorderStopsUseCase,
  createScheduleTripUseCase,
  createStartTripUseCase,
  createUpdateCargoUseCase,
  createUpdateExpenseUseCase,
  createUpdateStopUseCase,
  createUpdateTripStatusUseCase,
  createUpdateTripUseCase,
} from "./useCases";
