/** Layout del sheet de partida de cobro — alineado a substitutionSheetLayout. */
export {
  SUBSTITUTION_SHEET_CONTENT_CLASS as INVOICE_CONCEPT_SHEET_CONTENT_CLASS,
  SUBSTITUTION_SHEET_HEADER_CLASS as INVOICE_CONCEPT_SHEET_HEADER_CLASS,
  SUBSTITUTION_SHEET_BODY_CLASS as INVOICE_CONCEPT_SHEET_BODY_CLASS,
  SUBSTITUTION_SHEET_FOOTER_CLASS as INVOICE_CONCEPT_SHEET_FOOTER_CLASS,
  SUBSTITUTION_SHEET_PRIMARY_BUTTON_CLASS as INVOICE_CONCEPT_SHEET_PRIMARY_BUTTON_CLASS,
} from "./substitutionSheetLayout";
